//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Suscriptor
    {
        public int id { get; set; }
        [Required(ErrorMessage = "El valor es requerido.")]
        [EmailAddress(ErrorMessage = "El valor no es un E-Mail valido.")]
        public string email { get; set; }
    }
}
